name: Glass
version: 0.2
author: DodgeWhale
main: net.dodgewhale.glass.GlassMain
commands:
  gm:
    usage: /gm
    description: Updates player's gamemode
  health:
    usage: /health
    description: Displays player's health