name: Glass
version: 0.3
author: DodgeWhale
main: net.dodgewhale.glass.GlassMain
commands:
  gm:
    usage: /gm
    description: Updates player's gamemode
  health:
    usage: /health
    description: Displays player's health
  sync:
    usage: /sync
    description: Saves player's data